### ISSUE TITLE
bad installation. need help.

### ISSUE THREAD

**Issue by ghost** [kwohlfahrt/tiffutil#1]
sorry. I don't have too much idea of manjaro arm ( I am used to debian distros) and pip and pip3 works horrible on arm. I assume because there is no platform packages, because whenever Ive tried it on the past I dont have another choice than go back installing the python libs from the repo.
whatever. the problem its the next, I finish installing this project with python install setup.py but...

when Ive try to execute it:

```

[pilab@pilab ~]$ tiffutil
Traceback (most recent call last):
  File "/usr/bin/tiffutil", line 11, in <module>
    load_entry_point('tiffutil==0.1.2', 'console_scripts', 'tiffutil')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/lib/python3.7/site-packages/tiffutil-0.1.2-py3.7.egg/tiffutil/main.py", line 15, in <module>
  File "/usr/lib/python3.7/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.project'
[pilab@pilab ~]$

```

I've couldn't find this python module on the repo like other python modules.
weird, there is not much reference and I need to pack a program with electron-build

**Comment by kwohlfahrt** [comment]
Sorry, I don't quite understand the issue. Could you list all the steps you did to install this module? Did you install it with `pip`, or a different package manager?

**Comment by ghost** [comment]
Ive use the installation from source.

**Comment by kwohlfahrt** [comment]
I'm afraid I don't have enough information to help you. Can you run the following steps, in an empty directory, and post the output of each:

1. Create a fresh virtual environment: `python3 -m venv venv`
2. Activate the virtual environment: `source venv/bin/activate`
3. Install this package: `pip3 install git+https://github.com/kwohlfahrt/tiffutil.git`
4. Check the version of this package: `which tiffutil`
5. Run this package: `tiffutil --help`

**Comment by ghost** [comment]
Okay sir, Im on another distro. So I will close the issue... and if I had any similar problem i will reopen it. Thanks!
